/* tslint:disable */
/* eslint-disable */
/**
 * Babylon PTE API
 * Babylon Public Test Environment (PTE) API specification.
 *
 * The version of the OpenAPI document: 1.0.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRule
 */
export interface AuthRule {
    /**
     * 
     * @type {string}
     * @memberof AuthRule
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRule
     */
    rule: string;
}

export function AuthRuleFromJSON(json: any): AuthRule {
    return AuthRuleFromJSONTyped(json, false);
}

export function AuthRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'rule': json['rule'],
    };
}

export function AuthRuleToJSON(value?: AuthRule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'rule': value.rule,
    };
}

