/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users": {
    /** Optional extended description in CommonMark or HTML. */
    get: {
      responses: {
        /** A JSON array of user names */
        200: {
          content: {
            "application/json": string[];
          };
        };
      };
    };
  };
}

export interface components {}

export interface operations {}

export interface external {}
