/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/show/{address}": {
    get: {
      parameters: {};
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["ShowResponse"];
          };
        };
        /** Runtime failure */
        500: unknown;
      };
    };
  };
}

export interface components {
  schemas: {
    ShowResponse: {
      package?: string;
      /** Format: int64 */
      code_size?: number;
    };
  };
}

export interface operations {}

export interface external {}
